### ISSUE TITLE
Why .md instead of .txt in Feature list?

### ISSUE THREAD

**Issue by buzz2vatsal** [Learnovate/Library-Portal#6]
I know .md is supported by Github and its official. But isn't it easy to work with .txt for feature list? Easy to pull and merge the text file which they created on their local machines.  Feel free to explain the reason for .md

**Comment by dhruvin2910** [comment]
You might not know but `. md` compiles down to plain old `.html`. Every open source project must have (in my opinion) Documentation.

1. Documentation should be **browesable**, and hence should have links to follow. HTML has it inbuilt (anchor tags).

2. But writing and maintaining HTML docs is tedious because hey everybody hates tags.

3. Hence markdown is just like text document but it's browesable and looks readable online.

4. You may find writing in MD daunting at first because when you write specs, all you wanted is to write specs! No markdown ui sugaring.

5. But txt documents aren't structuted. Neither can be. One or other way you will have to find a standard to lay out text files and everybody contributing in the project will have to follow.

6. MD is what you'll need. It structures the document, make it readable even in text mode, compiles to HTML making that file browesable.

> Markdown makes files documents.

**Comment by buzz2vatsal** [comment]
Ohkay...Good one..
